import { Drawer, DrawerContent, DrawerSide } from '@/components/Drawer'
import Navbar from '@/components/Navbar'
import MainContent from '@/components/MainContent'
import Sidebar from '@/components/Sidebar'

// import { Inter } from 'next/font/google'
import '@/app/tailwind.css'
import '@/app/globals.css'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      {/* <body className={inter.className}>{children}</body> */}
      <body>
        <Drawer>
          <DrawerContent>
            <Navbar />
            <MainContent>{children}</MainContent>
          </DrawerContent>

          <DrawerSide>
            <Sidebar />
          </DrawerSide>
        </Drawer>
      </body>
    </html>
  )
}
